#!/usr/bin/env node
// Xerus Platform MCP Server - Stub
//
// This file is a placeholder in the workspace template.
// The real implementation is generated by the backend scaffold service
// during workspace creation (DaytonaProvider.scaffoldWorkspace).
//
// If you see this error, the scaffold process did not generate the
// platform MCP server. Check the backend scaffold logs.

process.stderr.write(
  '[xerus-platform] ERROR: Platform MCP server not initialized.\n' +
  'This workspace has not been scaffolded by the backend.\n' +
  'The scaffold service generates this file during workspace creation.\n' +
  'See: xerus_backend/src/domains/execution/workspace/workspace-initializer.service.ts\n'
);
process.exit(1);
